---
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Create WebSite directory
  file: 
      path: /data/wwwroot/{{caddy_appname}}
      state: directory
      owner: caddy
      group: caddy

- name: Copy Caddy Configuration 
  template: 
    src: Caddyfile.j2 
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy    
  
- name: Start caddy
  service:
    name: caddy
    state: restarted
    enabled: yes
    
- name: Create link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
    - {src: ,dest: /data/apps/frappe}
 
  
# Check version
- block:
  - name: Check caddy Version
    shell: sudo echo $(caddy version) | sudo tee -a /data/logs/install_version.txt

# check service state
  - name: Check Candy Service
    shell: systemctl status caddy | grep Active*
    register: check_caddy_service
    notify: check_caddy_service

